#!/bin/sh
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Real_univ_45PN.txt --target ./txt/target_Art_univ.txt --gpu $1 --relationship_path relationship/source_Real_univ_45PN.npy
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Real_univ_45PN.txt --target ./txt/target_Clipart_univ.txt --gpu $1 --relationship_path relationship/source_Real_univ_45PN.npy
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Real_univ_45PN.txt --target ./txt/target_Product_univ.txt --gpu $1 --relationship_path relationship/source_Real_univ_45PN.npy
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Product_univ_45PN.txt --target ./txt/target_Real_univ.txt --gpu $1 --relationship_path relationship/source_Product_univ_45PN.npy
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Product_univ_45PN.txt --target ./txt/target_Art_univ.txt --gpu $1 --relationship_path relationship/source_Product_univ_45PN.npy
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Product_univ_45PN.txt --target ./txt/target_Clipart_univ.txt --gpu $1 --relationship_path relationship/source_Product_univ_45PN.npy
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Art_univ_45PN.txt --target ./txt/target_Clipart_univ.txt --gpu $1 --relationship_path relationship/source_Art_univ_45PN.npy
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Art_univ_45PN.txt --target ./txt/target_Product_univ.txt --gpu $1 --relationship_path relationship/source_Art_univ_45PN.npy
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Art_univ_45PN.txt --target ./txt/target_Real_univ.txt --gpu $1 --relationship_path relationship/source_Art_univ_45PN.npy
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Clipart_univ_45PN.txt --target ./txt/target_Real_univ.txt --gpu $1 --relationship_path relationship/source_Clipart_univ_45PN.npy
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Clipart_univ_45PN.txt --target ./txt/target_Product_univ.txt --gpu $1 --relationship_path relationship/source_Clipart_univ_45PN.npy
python train_dance_co.py --config configs/officehome-train-config_OPDA.yaml --source ./txt/source_Clipart_univ_45PN.txt --target ./txt/target_Art_univ.txt --gpu $1 --relationship_path relationship/source_Clipart_univ_45PN.npy
